DROP TABLE IF EXISTS users, items, bookings, comments;

CREATE TABLE IF NOT EXISTS users
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name       VARCHAR(50)      NOT NULL,
  email      VARCHAR(50)      NOT NULL UNIQUE,
  CONSTRAINT pk_user          PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        VARCHAR(50)       NOT NULL,
    description VARCHAR(250)      NOT NULL,
    available   boolean,
    owner_id    BIGINT            NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT  pk_item           PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id          BIGINT GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start_date  TIMESTAMP         WITHOUT TIME ZONE                  NOT NULL,
    end_date    TIMESTAMP         WITHOUT TIME ZONE                  NOT NULL,
    item_id     BIGINT            REFERENCES items (id) ON DELETE CASCADE,
    booker_id   BIGINT            REFERENCES users (id) ON DELETE CASCADE,
    status      VARCHAR(50),
    CONSTRAINT  pk_booking        PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text         VARCHAR(250)                                        NOT NULL,
    item_id      BIGINT           REFERENCES items (id) ON DELETE CASCADE,
    author_id    BIGINT           REFERENCES users (id) ON DELETE CASCADE,
    created_date TIMESTAMP        WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT   pk_comment       PRIMARY KEY (id)
);
